---
- hosts: ubuntu
  become: yes
  gather_facts: false
  tasks:

    - name: Install python
      apt:
        pkg: python3
        state: present
        update_cache: yes

    - name: Installs Ngix
      apt:
        pkg: nginx
        state: present
      notify:
         - Nginx start
         - Nginx startup

    - name: Checking for the existence of the user nginx
      shell: cat /etc/passwd | grep nginx
      register: user_exist_status
      ignore_errors: true

    - name: Create Nginx user
      command: useradd --no-create-home nginx
      when: user_exist_status is failed

    - name: Change default nginx configan
      copy:
         src: ./files/nginx.conf
         dest: /etc/nginx/nginx.conf
         owner: root
         mode: 0644

    - name: Remove default nginx site config
      file:
         name: /etc/nginx/sites-enabled/default
         state: absent

    - name: Remove domain nginx site config
      file:
         name: /etc/nginx/sites-enabled/{{domain_name}}
         state: absent

    - name: Add static site
      copy:
          src: ./files/index.html
          dest: /var/www/html/index.html
          owner: root
          mode: 0644
      register: site_not_found
      ignore_errors: true

    - name: Setup site config
      template:
          src: ./files/site_config.j2
          dest: /etc/nginx/sites-available/{{domain_name}}
          owner: root
          mode: 0644
      when: site_not_found is succeeded

    - name: Setup redirect on google
      template:
          src: ./files/redirect_config.j2
          dest: /etc/nginx/sites-available/{{domain_name}}
          owner: root
          mode: 0644
      when: site_not_found is failed

    - name: Enable site
      file:
         src: /etc/nginx/sites-available/{{domain_name}}
         dest: /etc/nginx/sites-enabled/{{domain_name}}
         state: link
      notify:
         - Nginx reload


    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
         pkg: "{{ item }}"
         state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg

    - name: Work out the distribution
        command: lsb_release -sc
        register: lsb_release


    - apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_release.stdout}} stable

    - name: Install docker 19.03.12
      apt:
        pkg: "{{ item }}"
        update_cache: yes
      with_items:
        - docker-ce=5:19.03.12~3-0~ubuntu-bionic
        - docker-ce-cli=5:19.03.12~3-0~ubuntu-bionic
        - containerd.io

  handlers:
    - name: Nginx start
      service:
        name: nginx
        state: started

    - name: Nginx startup
      service:
        name: nginx
        enabled: yes

    - name: Nginx reload
      service:
        name: nginx
        state: reloaded
